---
name: concourse

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  networks: 
  - name: default
    static_ips: [((atc_static_ip))]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: https://((atc_static_ip)):443
      basic_auth_username: atc
      basic_auth_password: ((atc_basic_auth_password))
      tls_cert: ((atc_tls_cert.certificate))
      tls_key: ((atc_tls_cert.private_key))
      tls_bind_port: 443
      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: default
  stemcell: trusty
  persistent_disk_type: large
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: atc
        password: ((postgresql_password))

- name: worker
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
  - name: atc_basic_auth_password
    type: password
  - name: postgresql_password
    type: password
  - name: default_ca
    type: certificate
    options:
      is_ca: true
      common_name: bosh-ca
  - name: atc_tls_cert
    type: certificate
    options: 
      ca: default_ca
      common_name: ((atc_static_ip))
      alternative_names: [((atc_static_ip))]

